name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup JDK
        uses: actions/setup-java@1.4.2
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@2.1.4
        with:
          name: app
          path: app/build/output/apk/debug/app-debug.apk
